name: Kotlin bonus hw a check

on:
    pull_request:
        types:
        - opened
        - synchronize

jobs:
    build:
        runs-on: [self-hosted, kotlin]
        timeout-minutes: 10
        steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v3
          with:
              java-version: 17
              distribution: adopt
        - name: Setup Gradle
          uses: gradle/gradle-build-action@v2
        - name: Build with Gradle
          run: ./gradlew build
        - name: Check ktlint and datekt configuration
          run: |
              ./gradlew tasks --all > gradle-tasks.txt
              if [ $(grep -E '^detekt' gradle-tasks.txt | wc -l) -eq 0 ];
                then echo "detekt is not installed" && exit 1;
              fi
              if [ $(grep -E '^ktlint' gradle-tasks.txt | wc -l) -eq 0 ];
                then echo "ktlint is not installed" && exit 1;
              fi
          shell: bash
